[package]
name = "human_male"
version = "0.0.3-snap7-dev"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description="A humanoid."
homepage="https://starwolves.io"
repository="https://gitlab.starwolves.io/starwolves/space"
documentation="https://docs.sf.starwolves.io"
license-file="LICENSE"
edition = "2021"

[dependencies.bevy]
version = "0.8.0"
default-features = false

[dependencies]
bevy_rapier3d = "0.16.0"

entity = { path = "../../core/entity" }
physics = { path = "../../core/physics" }
chat = { path = "../../core/chat" }
data_link = { path = "../../core/data_link" }
inventory_item = { path = "../../core/inventory_item" }
inventory_api = { path = "../../core/inventory_api" }
map = { path = "../../core/map" }
rigid_body = { path = "../../core/rigid_body" }
player_controller = { path = "../../core/player_controller" }
combat = { path = "../../core/combat" }
networking = { path = "../../core/networking" }
server = { path = "../../core/server" }
humanoid = { path = "../../core/humanoid" }
pawn = { path = "../../core/pawn" }
showcase = { path = "../../core/showcase" }
jumpsuit_security = { path = "../jumpsuit_security" }
helmet_security = { path = "../helmet_security" }
pistol_l1 = { path = "../pistol_l1" }
construction_tool_admin = { path = "../construction_tool_admin" }
