[package]
name = "human_male"
version = "0.0.3"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description = "A humanoid."
homepage = "https://starwolves.io"
repository = "https://gitlab.starwolves.io/starwolves/space"
documentation = "https://docs.sf.starwolves.io"
license-file = "LICENSE"
edition = "2021"




[dependencies.bevy]
version = "0.12"

default-features = false

[dependencies]
bevy_xpbd_3d = { version = "0.3.2" , features = ["enhanced-determinism"], git = "https://github.com/Jondolf/bevy_xpbd.git", branch="main"}

inventory = { path = "../../core/inventory" }
player = { path = "../../core/player"}
entity = { path = "../../core/entity" }
map = { path = "../../core/map" }
controller = { path = "../../core/controller" }
combat = { path = "../../core/combat"}
graphics = { path = "../../core/graphics"}
cameras = { path = "../../core/cameras"}
networking = { path = "../../core/networking" }
resources = { path = "../../core/resources" }
humanoid = { path = "../../core/humanoid" }
pawn = { path = "../../core/pawn" }
setup_menu = { path = "../../core/setup_menu"}
physics = { path = "../../core/physics"}
basic_console_commands = { path = "../../core/basic_console_commands" }
construction_tool = { path = "../construction_tool" }
