[package]
name = "setup_menu"
version = "0.0.3"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description = "Text character setup ui."
homepage = "https://starwolves.io"
repository = "https://gitlab.starwolves.io/starwolves/space"
documentation = "https://docs.sf.starwolves.io"
license-file = "LICENSE"
edition = "2021"



[dependencies.bevy]
version = "0.9.1"
default-features = false

[dependencies]
iyes_loopless = "0.9.1"
serde = "1.0.150"
typename = "0.1.2"

networking = { path = "../networking" }
resources = { path = "../resources" }
player = { path = "../player" }
motd = { path = "../motd" }
text_api = { path = "../text_api" }
controller = { path = "../controller" }
