[package]
name = "player"
version = "0.0.3-snap8-dev"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description = "Player resources."
homepage = "https://starwolves.io"
repository = "https://gitlab.starwolves.io/starwolves/space"
documentation = "https://docs.sf.starwolves.io"
license-file = "LICENSE"
edition = "2021"

[features]
server = []
client = []

[dependencies.bevy]
version = "0.9.1"
default-features = false

[dependencies]
serde = "1.0.150"
rand = "0.8.5"
bevy_renet = "0.0.6"
typename = "0.1.2"

networking = { path = "../networking", features = ["server"] }
text_api = { path = "../text_api", features = ["server"] }
resources = { path = "../resources", features = ["server"] }
pawn = { path = "../pawn", features = ["server"] }
