[package]
name = "player"
version = "0.0.3"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description = "Player resources."
homepage = "https://starwolves.io"
repository = "https://gitlab.starwolves.io/starwolves/space"
documentation = "https://docs.sf.starwolves.io"
license-file = "LICENSE"
edition = "2021"


[dependencies.bevy]
version = "0.11.0"
default-features = false

[dependencies]
serde = "1.0.150"
rand = "0.8.5"
ehttp = "0.2.0"
typename = "0.1.2"
local_ipaddress = "0.1.3"
form_urlencoded = "1.1.0"
futures-lite = "1.13.0"
serde_json = "1.0.95"

bevy_renet = "0.0.9"
networking = { path = "../networking" }
resources = { path = "../resources" }
graphics = { path = "../graphics" }
pawn = { path = "../pawn" }
cameras = { path = "../cameras" }
entity = { path = "../entity" }
