[package]
name = "player"
version = "0.0.3"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description = "Player resources."
homepage = "https://starwolves.io"
repository = "https://gitlab.starwolves.io/starwolves/space"
documentation = "https://docs.sf.starwolves.io"
license-file = "LICENSE"
edition = "2021"


[dependencies.bevy]
version = "0.10.0"
default-features = false

[dependencies]
serde = "1.0.150"
rand = "0.8.5"
bevy_renet = { git = "https://github.com/lucaspoffo/renet.git" }
typename = "0.1.2"
bevy_atmosphere = { git = "https://github.com/BrandonDyer64/bevy_atmosphere.git" , branch = "bevy-v0.10"  }

networking = { path = "../networking" }
resources = { path = "../resources" }
graphics = { path = "../graphics" }
pawn = { path = "../pawn" }
cameras = { path = "../cameras" }
entity = { path = "../entity" }
