[package]
name = "computers"
version = "0.0.3-snap8-dev"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description="Interactable computers."
homepage="https://starwolves.io"
repository="https://gitlab.starwolves.io/starwolves/space"
documentation="https://docs.sf.starwolves.io"
license-file="LICENSE"
edition = "2021"


[features]
server = []
client = []

[dependencies.bevy]
version = "0.9.0"
default-features = false


[dependencies]
bevy_rapier3d = "0.19.0"
serde_json = "1.0.87"

entity = { path = "../../core/entity" ,  features=["server"]}
rigid_body = { path = "../../core/rigid_body",  features=["server"] }
text_api = { path = "../../core/text_api",  features=["server"] }
combat = { path = "../../core/combat",  features=["server"] }
resources = { path = "../../core/resources" ,  features=["server"]}
