[package]
name = "computers"
version = "0.0.3"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description = "Interactable computers."
homepage = "https://starwolves.io"
repository = "https://gitlab.starwolves.io/starwolves/space"
documentation = "https://docs.sf.starwolves.io"
license-file = "LICENSE"
edition = "2021"




[dependencies.bevy]
version = "0.11.0"
default-features = false


[dependencies]
bevy_xpbd_3d = { version = "0.2.0" , features = ["enhanced-determinism"], git = "https://github.com/starwolfy/bevy_xpbd.git", branch="fixedtime"}

entity = { path = "../../core/entity" }
text_api = { path = "../../core/text_api" }
combat = { path = "../../core/combat" }
resources = { path = "../../core/resources" }
physics = { path = "../../core/physics" }

