[package]
name = "airlocks"
version = "0.0.3-snap8-dev"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description = "Airlocks with authentication systems."
homepage = "https://starwolves.io"
repository = "https://gitlab.starwolves.io/starwolves/space"
documentation = "https://docs.sf.starwolves.io"
license-file = "LICENSE"
edition = "2021"

[features]
server = []
client = []

[dependencies.bevy]
version = "0.9.1"
default-features = false


[dependencies]
bevy_rapier3d = "0.19.0"
const_format = "0.2.30"

entity = { path = "../../core/entity", features = ["server"] }
networking = { path = "../../core/networking", features = ["server"] }
atmospherics = { path = "../../core/atmospherics", features = ["server"] }
map = { path = "../../core/map", features = ["server"] }
pawn = { path = "../../core/pawn", features = ["server"] }
sfx = { path = "../../core/sfx", features = ["server"] }
sounds = { path = "../sounds", features = ["server"] }
text_api = { path = "../../core/text_api", features = ["server"] }
combat = { path = "../../core/combat", features = ["server"] }
actions = { path = "../../core/actions", features = ["server"] }
gridmap = { path = "../../core/gridmap", features = ["server"] }
resources = { path = "../../core/resources", features = ["server"] }
math = { path = "../../core/math", features = ["server"] }
physics = { path = "../../core/physics", features = ["server"] }

