[package]
name = "airlocks"
version = "0.0.3"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description = "Airlocks with authentication systems."
homepage = "https://starwolves.io"
repository = "https://gitlab.starwolves.io/starwolves/space"
documentation = "https://docs.sf.starwolves.io"
license-file = "LICENSE"
edition = "2021"


[dependencies.bevy]
version = "0.11.0"
default-features = false

[dependencies]
bevy_xpbd_3d = {git = "https://github.com/Jondolf/bevy_xpbd.git", branch = "main"}
const_format = "0.2.30"

entity = { path = "../../core/entity" }
networking = { path = "../../core/networking" }
map = { path = "../../core/map" }
pawn = { path = "../../core/pawn" }
sfx = { path = "../../core/sfx" }
sounds = { path = "../sounds" }
text_api = { path = "../../core/text_api" }
combat = { path = "../../core/combat" }
actions = { path = "../../core/actions" }
gridmap = { path = "../../core/gridmap" }
resources = { path = "../../core/resources" }
physics = { path = "../../core/physics" }
