[package]
name = "world"
version = "0.0.3"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description = "World elements."
homepage = "https://starwolves.io"
repository = "https://gitlab.starwolves.io/starwolves/space"
documentation = "https://docs.sf.starwolves.io"
license-file = "LICENSE"
edition = "2021"

[dependencies]
bevy_atmosphere = { git = "https://github.com/GodGotzi/bevy_atmosphere.git" , rev = "c279833" }

resources = { path = "../resources" }

[dependencies.bevy]
version = "0.11.0"
default-features = false
