[package]
name = "hud"
version = "0.0.3"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description = "Player HUD."
homepage = "https://starwolves.io"
repository = "https://gitlab.starwolves.io/starwolves/space"
documentation = "https://docs.sf.starwolves.io"
license-file = "LICENSE"
edition = "2021"



[dependencies.bevy]
version = "0.9.1"
default-features = false

[dependencies]
iyes_loopless = "0.9.1"

resources = { path = "../resources"}
player = { path = "../player"}
networking = { path = "../networking"}
inventory = { path = "../inventory"}
