image: "rust:latest"

test:cargo:
  tags:
    - space
  script:
    - apt update -y
    - apt-get install g++ pkg-config libx11-dev libasound2-dev libudev-dev
    - rustc --version && cargo --version
    - cargo check
