image: "rust:latest"

before_script:
    - apk add g++ pkg-config libx11-dev libasound2-dev libudev-dev

test:cargo:
  tags:
    - space
  script:
    - rustc --version && cargo --version
    - cargo test --verbose
