image: "rust:latest"

test:cargo:
  tags:
    - space
  script:
    - rustc --version && cargo --version
    - cargo test
  cache:
    key: "$CI_JOB_NAME"
    untracked: true
    paths:
    - target/

