image: "rust:latest"

before-script:
 - apt-get install g++ pkg-config libx11-dev libasound2-dev libudev-dev

test:cargo:
  tags:
    - space
  script:
    - rustc --version && cargo --version
    - cargo check
