[package]
name = "construction_tool_admin"
version = "0.0.3-snap7-dev"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description="Admin construction tool."
homepage="https://starwolves.io"
repository="https://gitlab.starwolves.io/starwolves/space"
documentation="https://docs.sf.starwolves.io"
license-file="LICENSE"
edition = "2021"

[dependencies.bevy]
version = "0.8.1"
default-features = false

[dependencies]
doryen_fov = { path = "../../core/doryen_fov" }
rand = "0.8.5"
bevy_rapier3d = "0.16.2"

entity = { path = "../../core/entity" }
gridmap = { path = "../../core/gridmap" }
networking = { path = "../../core/networking" }
networking_macros = { path = "../../core/networking_macros" }
pawn = { path = "../../core/pawn" }
combat = { path = "../../core/combat" }
atmospherics = { path = "../../core/atmospherics" }
inventory_item = { path = "../../core/inventory_item" }
inventory_api = { path = "../../core/inventory_api" }
rigid_body = { path = "../../core/rigid_body" }
sfx = { path = "../../core/sfx" }
sounds = { path = "../sounds" }
chat_api = { path = "../../core/chat_api" }
physics = { path = "../../core/physics" }
actions = { path = "../../core/actions" }


data_converters = { path = "../../core/data_converters" }
server = { path = "../../core/server" }
math = { path = "../../core/math" }
