[package]
name = "construction_tool_admin"
version = "0.0.3"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description = "Admin construction tool."
homepage = "https://starwolves.io"
repository = "https://gitlab.starwolves.io/starwolves/space"
documentation = "https://docs.sf.starwolves.io"
license-file = "LICENSE"
edition = "2021"


[dependencies.bevy]
version = "0.9.1"
default-features = false

[dependencies]
rand = "0.8.5"
bevy_rapier3d = "0.19.0"
iyes_loopless = "0.9.1"

entity = { path = "../../core/entity" }
gridmap = { path = "../../core/gridmap" }
networking = { path = "../../core/networking" }
doryen_fov = { path = "../../core/doryen_fov" }
pawn = { path = "../../core/pawn" }
hud = { path = "../../core/hud" }
combat = { path = "../../core/combat" }
sfx = { path = "../../core/sfx" }
sounds = { path = "../sounds" }
text_api = { path = "../../core/text_api" }
actions = { path = "../../core/actions" }
ui = { path = "../../core/ui" }
resources = { path = "../../core/resources" }
math = { path = "../../core/math" }
physics = { path = "../../core/physics" }
inventory = { path = "../../core/inventory" }
basic_console_commands = { path = "../../core/basic_console_commands" }
