[package]
name = "rigid_body"
version = "0.0.0"
edition = "2021"

[dependencies.bevy]
version = "0.8.0"
default-features = false


[dependencies]
bevy_rapier3d = "0.15.0"

entity = { path = "../entity" }
physics = { path = "../physics" }
api = { path = "../api" }
