[package]
name = "health"
version = "0.0.0"
edition = "2021"

[dependencies.bevy]
version = "0.7.0"
default-features = false

[dependencies]
networking = { path = "../networking" }
api = { path = "../api" }
senser = { path = "../senser" }
