[package]
name = "resources"
version = "0.0.3"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description = "Additional resources."
homepage = "https://starwolves.io"
repository = "https://gitlab.starwolves.io/starwolves/space"
documentation = "https://docs.sf.starwolves.io"
license-file = "LICENSE"
edition = "2021"


[dependencies.bevy]
version = "0.12"

default-features = false

[dependencies]
bevy_xpbd_3d = { version = "0.3.2" , features = ["enhanced-determinism"]}
image = "0.24.6"
# Must match winit version used by Bevy.
winit = { version = "0.28", default-features = false }
serde = "1.0.177"
bevy_renet = { version = "0.0.10", git = "https://github.com/starwolfy/renet.git"}
