[package]
name = "resources"
version = "0.0.3"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description = "Additional resources."
homepage = "https://starwolves.io"
repository = "https://gitlab.starwolves.io/starwolves/space"
documentation = "https://docs.sf.starwolves.io"
license-file = "LICENSE"
edition = "2021"


[dependencies.bevy]
version = "0.10.1"
default-features = false

[dependencies]
bevy_rapier3d = "0.21.0"
image = "0.24.5"
# Must match winit version used by Bevy.
winit = { version = "0.28", default-features = false }
serde = "1.0.150"
