[package]
name = "ball"
version = "0.0.3"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description = "A ball."
homepage = "https://starwolves.io"
repository = "https://gitlab.starwolves.io/starwolves/space"
documentation = "https://docs.sf.starwolves.io"
license-file = "LICENSE"
edition = "2021"




[dependencies.bevy]
version = "0.13.0"

default-features = false

[dependencies]
bevy_xpbd_3d = { version = "0.4.2" , features = ["enhanced-determinism"]}
serde = "1.0.177"
typename = "0.1.2"

entity = { path = "../../core/entity" }
resources = { path = "../../core/resources" }
physics = { path = "../../core/physics" }
cameras = { path = "../../core/cameras" }
pawn = { path = "../../core/pawn" }
networking = { path = "../../core/networking" }
