use bevy::prelude::Color;
use bevy::math::Quat;

pub struct WorldEnvironment {
    adjustment_brightness: f32,
    adjustment_contrast: f32,
    adjustment_enabled: bool,
    adjustment_saturation : f32,
    ambient_light_color : Color,
    ambient_light_energy : f32,
    ambient_light_sky_contribution : f32,
    tonemap_auto_exposure : bool,
    tonemap_auto_exposure_max : f32,
    tonemap_auto_exposure_min : f32,
    tonemap_auto_exposure_grey : f32,
    tonemap_auto_exposure_speed : f32,
    camera_feed_id : i64,
    canvas_max_layer : i64,
    bg_color : Color,
    bg_energy : f32,
    background_mode : u8,
    sky_custom_fov : f32,
    sky_orientation : Quat,
    sky_rotation : Quat,
    dof_blur_far_amount : f32,
    dof_blur_far_distance : f32,
    dof_blur_far_enabled : bool,
    dof_blur_far_quality : u8,
    dof_blur_far_transition: f32,
    dof_blur_near_amount: f32,
    dof_blur_near_distance: f32,
    dof_blur_near_enabled : bool,
    dof_blur_near_quality : f32,
    dof_blur_near_transition : f32,
    fog_color : Color,
    fog_depth_begin : f32,
    fog_depth_curve : f32,
    fog_depth_enabled : bool,
    fog_depth_end : f32,
    fog_enabled : bool,
    fog_height_curve : f32,
    fog_height_enabled : bool,
    fog_height_max : f32,
    fog_height_min : f32,
    fog_sun_amount : f32,
    fog_sun_color : Color,
    fog_transmit_curve : f32,
    fog_transmit_enabled : bool,
    glow_bicubic_upscale_enabled : bool,
    glow_blend_mode : u8,
    glow_bloom : f32,
    glow_enabled : bool,
    glow_hdr_luminance_cap : f32,
    glow_hdr_bleed_scale : f32,
    glow_hdr_bleed_treshold  : f32,
    glow_intensity : f32,
    glow_strength : f32,
    ssr_depth_tolerance : f32,
    ssr_enabled : bool,
    ssr_fade_in : f32,
    ssr_fade_out : f32,
    ssr_max_steps : i64,
    ssr_rough : bool,
    ssao_ao_channel_affect : f32,
    ssao_bias : f32,
    ssao_blur : u8,
    ssao_color : Color,
    ssao_edge_sharpness : f32,
    ssao_enabled : bool,
    ssao_intensity : f32,
    ssao_intensity2 : f32,
    ssao_direct_light_affect : f32,
    ssao_quality : u8,
    ssao_radius : f32,
    ssao_radius2 : f32,
    tone_map_exposure : f32,
    tone_mapper : u8,
    tone_map_white : f32
}
