[package]
name = "construction_tool"
version = "0.0.3"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description = "Construction tool."
homepage = "https://starwolves.io"
repository = "https://gitlab.starwolves.io/starwolves/space"
documentation = "https://docs.sf.starwolves.io"
license-file = "LICENSE"
edition = "2021"


[dependencies.bevy]
version = "0.10.1"
default-features = false

[dependencies]
bevy_xpbd_3d = "0.1.0"

entity = { path = "../../core/entity" }
gridmap = { path = "../../core/gridmap" }
networking = { path = "../../core/networking" }
hud = { path = "../../core/hud" }
combat = { path = "../../core/combat" }
sfx = { path = "../../core/sfx" }
actions = { path = "../../core/actions" }
ui = { path = "../../core/ui" }
resources = { path = "../../core/resources" }
physics = { path = "../../core/physics" }
inventory = { path = "../../core/inventory" }
basic_console_commands = { path = "../../core/basic_console_commands" }
