[package]
name = "sounds"
version = "0.0.3-snap8-dev"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description = "Sound effect storage."
homepage = "https://starwolves.io"
repository = "https://gitlab.starwolves.io/starwolves/space"
documentation = "https://docs.sf.starwolves.io"
license-file = "LICENSE"
edition = "2021"


[features]
server = []
client = []

[dependencies.bevy]
version = "0.9.1"
default-features = false

[dependencies]
rand = "0.8.5"

sfx = { path = "../../core/sfx", features = ["server"] }
