[package]
name = "networking"
version = "0.0.3-snap8-dev"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description = "Netcode."
homepage = "https://starwolves.io"
repository = "https://gitlab.starwolves.io/starwolves/space"
documentation = "https://docs.sf.starwolves.io"
license-file = "LICENSE"
edition = "2021"

[features]
server = []
client = []

[dependencies.bevy]
version = "0.9.1"
default-features = false

[dependencies]
bevy_renet = "0.0.6"
bincode = "1.3.3"
local_ipaddress = "0.1.3"
serde = "1.0.150"
typename = "0.1.2"
iyes_loopless = "0.9.1"
math = { path = "../math", features = ["server"] }
resources = { path = "../resources", features = ["server"] }
