[package]
name = "networking"
version = "0.0.0"
edition = "2021"

[dependencies.bevy]
version = "0.7.0"
default-features = false

[dependencies]
bevy_renet = "0.0.3"
bincode = "1.3.3"
local_ipaddress = "0.1.3"

api = { path = "../api" }
