[package]
name = "networking"
version = "0.0.3"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description = "Netcode."
homepage = "https://starwolves.io"
repository = "https://gitlab.starwolves.io/starwolves/space"
documentation = "https://docs.sf.starwolves.io"
license-file = "LICENSE"
edition = "2021"



[dependencies.bevy]
version = "0.10.0"
default-features = false

[dependencies]
bevy_renet = { git = "https://github.com/lucaspoffo/renet.git" }
bincode = "1.3.3"
local_ipaddress = "0.1.3"
serde = "1.0.150"
typename = "0.1.2"
resources = { path = "../resources" }
