[package]
name = "networking"
version = "0.0.3"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description = "Netcode."
homepage = "https://starwolves.io"
repository = "https://gitlab.starwolves.io/starwolves/space"
documentation = "https://docs.sf.starwolves.io"
license-file = "LICENSE"
edition = "2021"



[dependencies.bevy]
version = "0.11.3"

default-features = false

[dependencies]
bevy_renet = "0.0.9"
bincode = "1.3.3"
local_ipaddress = "0.1.3"
serde = "1.0.177"
typename = "0.1.2"
ehttp = "0.3.0"
serde_json = "1.0.104"
form_urlencoded = "1.2.0"
futures-lite = "1.13.0"
bevy_xpbd_3d = { version = "0.2.0" , features = ["enhanced-determinism"], git = "https://github.com/Jondolf/bevy_xpbd.git", branch="main"}

resources = { path = "../resources" }
token = { path = "../token" }
