[package]
name = "pawn"
version = "0.0.3"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description = "Pawns are controllable entities by either players or AI."
homepage = "https://starwolves.io"
repository = "https://gitlab.starwolves.io/starwolves/space"
documentation = "https://docs.sf.starwolves.io"
license-file = "LICENSE"
edition = "2021"



[dependencies.bevy]
version = "0.10.1"
default-features = false

[dependencies]
bevy_xpbd_3d = "0.1.0"

networking = { path = "../networking"}
actions = { path = "../actions" }
resources = { path = "../resources" }
entity = { path = "../entity" }
