[package]
name = "pawn"
version = "0.0.3"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description = "Pawns are controllable entities by either players or AI."
homepage = "https://starwolves.io"
repository = "https://gitlab.starwolves.io/starwolves/space"
documentation = "https://docs.sf.starwolves.io"
license-file = "LICENSE"
edition = "2021"



[dependencies.bevy]
version = "0.12.1"

default-features = false

[dependencies]
bevy_xpbd_3d = { version = "0.3.2" , features = ["enhanced-determinism"]}
serde = "1.0.177"
typename = "0.1.2"
bevy_renet = { version = "0.0.10", git = "https://github.com/starwolfy/renet.git"}
bincode = "1.3.3"
itertools = "0.12.0"

networking = { path = "../networking"}
actions = { path = "../actions" }
resources = { path = "../resources" }
entity = { path = "../entity" }
cameras = { path = "../cameras" }
