[package]
name = "pawn"
version = "0.0.3-snap8-dev"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description="Pawns are controllable entities by either players or AI."
homepage="https://starwolves.io"
repository="https://gitlab.starwolves.io/starwolves/space"
documentation="https://docs.sf.starwolves.io"
license-file="LICENSE"
edition = "2021"

[features]
server = []
client = []

[dependencies.bevy]
version = "0.9.0"
default-features = false

[dependencies]
bevy_rapier3d = "0.19.0"
bevy_renet = "0.0.6"
bincode = "1.3.3"

networking = { path = "../networking",  features=["server"] }
networking_macros = { path = "../networking_macros" ,  features=["server"]}
actions = { path = "../actions",  features=["server"] }
resources = { path = "../resources",  features=["server"] }
math = { path = "../math",  features=["server"] }
entity = { path = "../entity",  features=["server"] }
text_api = { path = "../text_api",  features=["server"] }
player = { path = "../player",  features=["server"] }
