[package]
name = "physics"
version = "0.0.3"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description = "Physics logic for entities."
homepage = "https://starwolves.io"
repository = "https://gitlab.starwolves.io/starwolves/space"
documentation = "https://docs.sf.starwolves.io"
license-file = "LICENSE"
edition = "2021"



[dependencies.bevy]
version = "0.10.1"
default-features = false

[dependencies]
bevy_rapier3d = { version = "0.21.0", features = [
    "enhanced-determinism",
]}

entity = { path = "../entity"}
networking = { path = "../networking" }
resources = { path = "../resources"}
