[package]
name = "physics"
version = "0.0.3-snap8-dev"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description = "Physics logic for entities."
homepage = "https://starwolves.io"
repository = "https://gitlab.starwolves.io/starwolves/space"
documentation = "https://docs.sf.starwolves.io"
license-file = "LICENSE"
edition = "2021"

[features]
server = []
client = []

[dependencies.bevy]
version = "0.9.0"
default-features = false

[dependencies]
bevy_rapier3d = "0.19.0"

entity = { path = "../entity", features = ["server"] }
math = { path = "../math", features = ["server"] }
networking = { path = "../networking", features = ["server"] }
