[package]
name = "helmet_security"
version = "0.0.3-snap7-dev"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description="Wearable helmet."
homepage="https://starwolves.io"
repository="https://gitlab.starwolves.io/starwolves/space"
documentation="https://docs.sf.starwolves.io"
license-file="LICENSE"
edition = "2021"

[dependencies.bevy]
version = "0.8.1"
default-features = false

[dependencies]
bevy_rapier3d = "0.16.2"

entity = { path = "../../core/entity" }
inventory_item = { path = "../../core/inventory_item" }
inventory_api = { path = "../../core/inventory_api" }
rigid_body = { path = "../../core/rigid_body" }
combat = { path = "../../core/combat" }
data_converters = { path = "../../core/data_converters" }
server = { path = "../../core/server" }
