[package]
name = "helmet_security"
version = "0.0.0"
edition = "2021"


[dependencies.bevy]
version = "0.7.0"
default-features = false

[dependencies]
bevy_rapier3d = "0.15.0"

entity = { path = "../../core/entity" }
inventory_item = { path = "../../core/inventory_item" }
rigid_body = { path = "../../core/rigid_body" }
api = { path = "../../core/api" }
