[package]
name = "helmet_security"
version = "0.0.3-snap8-dev"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description = "Wearable helmet."
homepage = "https://starwolves.io"
repository = "https://gitlab.starwolves.io/starwolves/space"
documentation = "https://docs.sf.starwolves.io"
license-file = "LICENSE"
edition = "2021"




[dependencies.bevy]
version = "0.9.1"
default-features = false

[dependencies]
bevy_rapier3d = "0.19.0"

entity = { path = "../../core/entity" }
combat = { path = "../../core/combat" }
resources = { path = "../../core/resources" }
physics = { path = "../../core/physics" }
inventory = { path = "../../core/inventory"}
basic_console_commands = { path = "../../core/basic_console_commands"}

