[package]
name = "setup_ui"
version = "0.0.3-snap8-dev"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description="Text character setup ui."
homepage="https://starwolves.io"
repository="https://gitlab.starwolves.io/starwolves/space"
documentation="https://docs.sf.starwolves.io"
license-file="LICENSE"
edition = "2021"

[features]
server = []
client = []

[dependencies.bevy]
version = "0.9.0"
default-features = false

[dependencies]
bincode = "1.3.3"
bevy_renet = "0.0.6"

networking = { path = "../networking",  features=["server"] }
entity = { path = "../entity",  features=["server"] }
resources = { path = "../resources",  features=["server"] }
player = { path = "../player",  features=["server"] }
motd = { path = "../motd",  features=["server"] }
text_api = { path = "../text_api",  features=["server"] }
controller = { path = "../controller",  features=["server"] }
console_commands = { path = "../console_commands",  features=["server"] }
