[package]
name = "sfx"
version = "0.0.3"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description = "Sound effects."
homepage = "https://starwolves.io"
repository = "https://gitlab.starwolves.io/starwolves/space"
documentation = "https://docs.sf.starwolves.io"
license-file = "LICENSE"
edition = "2021"



[dependencies.bevy]
version = "0.11.0"
default-features = false

[dependencies]
rand = "0.8.5"
serde = "1.0.150"
typename = "0.1.2"
const_format = "0.2.30"

entity = { path = "../entity" }
networking = { path = "../networking" }
resources = { path = "../resources" }
