[package]
name = "sfx"
version = "0.0.0"
edition = "2021"

[dependencies.bevy]
version = "0.7.0"
default-features = false

[dependencies]
rand = "0.8.5"

entity = { path = "../entity" }
api = { path = "../api" }
