[package]
name = "counter_windows"
version = "0.0.3"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description = "Interactle windows with authorization systems."
homepage = "https://starwolves.io"
repository = "https://gitlab.starwolves.io/starwolves/space"
documentation = "https://docs.sf.starwolves.io"
license-file = "LICENSE"
edition = "2021"


[dependencies.bevy]
version = "0.9.1"
default-features = false

[dependencies]
bevy_rapier3d = "0.20.0"
const_format = "0.2.30"

entity = { path = "../../core/entity" }
networking = { path = "../../core/networking" }
map = { path = "../../core/map" }
pawn = { path = "../../core/pawn" }
sfx = { path = "../../core/sfx" }
sounds = { path = "../sounds" }
text_api = { path = "../../core/text_api" }
combat = { path = "../../core/combat" }
actions = { path = "../../core/actions" }
gridmap = { path = "../../core/gridmap" }
resources = { path = "../../core/resources" }
math = { path = "../../core/math" }
airlocks = { path = "../airlocks" }
physics = { path = "../../core/physics" }
