[package]
name = "counter_windows"
version = "0.0.3"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description = "Interactle windows with authorization systems."
homepage = "https://starwolves.io"
repository = "https://gitlab.starwolves.io/starwolves/space"
documentation = "https://docs.sf.starwolves.io"
license-file = "LICENSE"
edition = "2021"


[dependencies.bevy]
version = "0.13.1"

default-features = false

[dependencies]
bevy_xpbd_3d = { version = "0.4.2" , features = ["enhanced-determinism"]}
bevy_renet = { version = "0.0.11", git = "https://github.com/starwolfy/renet.git"}

const_format = "0.2.31"

entity = { path = "../../core/entity" }
networking = { path = "../../core/networking" }
map = { path = "../../core/map" }
pawn = { path = "../../core/pawn" }
sfx = { path = "../../core/sfx" }
sounds = { path = "../sounds" }
text_api = { path = "../../core/text_api" }
combat = { path = "../../core/combat" }
actions = { path = "../../core/actions" }
gridmap = { path = "../../core/gridmap" }
resources = { path = "../../core/resources" }
airlocks = { path = "../airlocks" }
physics = { path = "../../core/physics" }
