[package]
name = "counter_windows"
version = "0.0.0"
edition = "2021"


[dependencies.bevy]
version = "0.8.0"
default-features = false

[dependencies]
bevy_rapier3d = "0.15.0"

entity = { path = "../../core/entity" }
networking = { path = "../../core/networking" }
atmospherics = { path = "../../core/atmospherics" }
map = { path = "../../core/map" }
pawn = { path = "../../core/pawn" }
sfx = { path = "../../core/sfx" }
sounds = { path = "../sounds" }
physics = { path = "../../core/physics" }
rigid_body = { path = "../../core/rigid_body" }
api = { path = "../../core/api" }
combat = { path = "../../core/combat" }
