[package]
name = "counter_windows"
version = "0.0.3-snap8-dev"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description="Interactle windows with authorization systems."
homepage="https://starwolves.io"
repository="https://gitlab.starwolves.io/starwolves/space"
documentation="https://docs.sf.starwolves.io"
license-file="LICENSE"
edition = "2021"


[features]
server = []
client = []

[dependencies.bevy]
version = "0.8.1"
default-features = false

[dependencies]
bevy_rapier3d = "0.18.0"

entity = { path = "../../core/entity",  features=["server"] }
networking = { path = "../../core/networking",  features=["server"] }
networking_macros = { path = "../../core/networking_macros" ,  features=["server"]}
atmospherics = { path = "../../core/atmospherics" ,  features=["server"]}
map = { path = "../../core/map",  features=["server"] }
pawn = { path = "../../core/pawn",  features=["server"] }
sfx = { path = "../../core/sfx",  features=["server"] }
sounds = { path = "../sounds" ,  features=["server"]}
physics = { path = "../../core/physics" ,  features=["server"]}
rigid_body = { path = "../../core/rigid_body" ,  features=["server"]}
chat_api = { path = "../../core/chat_api" ,  features=["server"]}
combat = { path = "../../core/combat" ,  features=["server"]}
actions = { path = "../../core/actions" ,  features=["server"]}
gridmap = { path = "../../core/gridmap",  features=["server"] }
data_converters = { path = "../../core/data_converters" ,  features=["server"]}
data_link = { path = "../../core/data_link" ,  features=["server"]}
resources = { path = "../../core/resources" ,  features=["server"]}
math = { path = "../../core/math",  features=["server"] }
gridmap_meta = { path = "../../core/gridmap_meta",  features=["server"] }
air_locks = { path = "../air_locks" ,  features=["server"]}
