[package]
name = "point_light"
version = "0.0.3"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description = "A bevy PointLight."
homepage = "https://starwolves.io"
repository = "https://gitlab.starwolves.io/starwolves/space"
documentation = "https://docs.sf.starwolves.io"
license-file = "LICENSE"
edition = "2021"




[dependencies.bevy]
version = "0.11.2"

default-features = false

[dependencies]

entity = { path = "../../core/entity"}
resources = { path = "../../core/resources" }

