[package]
name = "line_arrow"
version = "0.0.3-snap8-dev"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description="An arrow for pin pointing locations."
homepage="https://starwolves.io"
repository="https://gitlab.starwolves.io/starwolves/space"
documentation="https://docs.sf.starwolves.io"
license-file="LICENSE"
edition = "2021"


[features]
server = []
client = []

[dependencies.bevy]
version = "0.9.0"
default-features = false

[dependencies]
console_commands = { path = "../../core/console_commands" ,  features=["server"]}
entity = { path = "../../core/entity" ,  features=["server"]}
networking = { path = "../../core/networking",  features=["server"] }
resources = { path = "../../core/resources",  features=["server"] }

