[package]
name = "ui"
version = "0.0.3"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description = "UI elements."
homepage = "https://starwolves.io"
repository = "https://gitlab.starwolves.io/starwolves/space"
documentation = "https://docs.sf.starwolves.io"
license-file = "LICENSE"
edition = "2021"

[dependencies]
serde = "1.0.150"
typename = "0.1.2"

bevy_egui = { version = "0.19.0", default-features = false, features = [
    "manage_clipboard",
] }
networking = { path = "../networking" }
resources = { path = "../resources" }

[dependencies.bevy]
version = "0.9.1"
default-features = false
