[package]
name = "ui"
version = "0.0.3-snap8-dev"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description="UI elements."
homepage="https://starwolves.io"
repository="https://gitlab.starwolves.io/starwolves/space"
documentation="https://docs.sf.starwolves.io"
license-file="LICENSE"
edition = "2021"

[features]
client = []
server = []

[dependencies]
bevy_renet = "0.0.6"
bincode = "1.3.3"
serde = "1.0.147"

bevy_egui = {version = "0.17.1",default-features=false, features=["manage_clipboard"]}
networking = { path = "../networking",  features=["server"] }

[dependencies.bevy]
version = "0.9.0"
default-features = false
