[package]
name = "ui"
version = "0.0.3-snap8-dev"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description="UI elements."
homepage="https://starwolves.io"
repository="https://gitlab.starwolves.io/starwolves/space"
documentation="https://docs.sf.starwolves.io"
license-file="LICENSE"
edition = "2021"

[features]
client = []

[dependencies]
bevy_egui = {version = "0.16.1",default-features=false, features=["manage_clipboard"]}

[dependencies.bevy]
version = "0.8.1"
default-features = false
