[package]
name = "controller"
version = "0.0.3"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description = "Logic regarding connected clients."
homepage = "https://starwolves.io"
repository = "https://gitlab.starwolves.io/starwolves/space"
documentation = "https://docs.sf.starwolves.io"
license-file = "LICENSE"
edition = "2021"
[dependencies.bevy]
version = "0.11.0"
default-features = false



[dependencies]
bevy_renet = { git = "https://github.com/Olle-Lukowski/renet.git" , rev = "a5c508d" }
serde = "1.0.150"
typename = "0.1.2"

player = { path = "../player" }
networking = { path = "../networking" }
pawn = { path = "../pawn" }
combat = { path = "../combat"}
resources = { path = "../resources"}
