[package]
name = "controller"
version = "0.0.3-snap8-dev"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description="Logic regarding connected clients."
homepage="https://starwolves.io"
repository="https://gitlab.starwolves.io/starwolves/space"
documentation="https://docs.sf.starwolves.io"
license-file="LICENSE"
edition = "2021"
[dependencies.bevy]
version = "0.9.0"
default-features = false

[features]
server = []
client = []

[dependencies]
bevy_renet = "0.0.6"
bincode = "1.3.3"
serde = "1.0.147"

player = { path = "../player",  features=["server"] }
networking = { path = "../networking",  features=["server"] }
networking_macros = { path = "../networking_macros",  features=["server"] }
entity = { path = "../entity",  features=["server"] }
pawn = { path = "../pawn",  features=["server"] }
combat = { path = "../combat",  features=["server"] }

world_environment = { path = "../world_environment",  features=["server"] }
resources = { path = "../resources",  features=["server"] }
math = { path = "../math",  features=["server"] }
gi_probe = { path = "../../entities/gi_probe",  features=["server"] }
reflection_probe = { path = "../../entities/reflection_probe",  features=["server"] }
