[package]
name = "controller"
version = "0.0.3-snap8-dev"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description = "Logic regarding connected clients."
homepage = "https://starwolves.io"
repository = "https://gitlab.starwolves.io/starwolves/space"
documentation = "https://docs.sf.starwolves.io"
license-file = "LICENSE"
edition = "2021"
[dependencies.bevy]
version = "0.9.1"
default-features = false

[features]
server = []
client = []

[dependencies]
bevy_renet = "0.0.6"
serde = "1.0.150"
typename = "0.1.2"

player = { path = "../player", features = ["server"] }
networking = { path = "../networking", features = ["server"] }
pawn = { path = "../pawn", features = ["server"] }
combat = { path = "../combat", features = ["server"] }
resources = { path = "../resources", features = ["server"] }
math = { path = "../math", features = ["server"] }
