[package]
name = "world_environment"
version = "0.0.3-snap8-dev"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description = "World environment manages client-side graphics and post processing."
homepage = "https://starwolves.io"
repository = "https://gitlab.starwolves.io/starwolves/space"
documentation = "https://docs.sf.starwolves.io"
license-file = "LICENSE"
edition = "2021"

[features]
server = []
client = []

[dependencies.bevy]
version = "0.9.1"
default-features = false

[dependencies]
serde_json = "1.0.89"
serde = "1.0.150"
ron = "0.8.0"

resources = { path = "../resources", features = ["server"] }
