[package]
name = "map"
version = "0.0.3-snap7-dev"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description="The 2D mini-map that can display various data."
homepage="https://starwolves.io"
repository="https://gitlab.starwolves.io/starwolves/space"
documentation="https://docs.sf.starwolves.io"
license-file="LICENSE"
edition = "2021"

[features]
server = []
client = []

[dependencies.bevy]
version = "0.8.1"
default-features = false

[dependencies]
networking = { path = "../networking" ,  features=["server"]}
networking_macros = { path = "../networking_macros",  features=["server"] }
data_link = { path = "../data_link",  features=["server"] }
resources = { path = "../resources" ,  features=["server"]}
math = { path = "../math" ,  features=["server"]}
entity = { path = "../entity" ,  features=["server"]}
