[package]
name = "omni_light"
version = "0.0.3-snap7-dev"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description="The main source of light."
homepage="https://starwolves.io"
repository="https://gitlab.starwolves.io/starwolves/space"
documentation="https://docs.sf.starwolves.io"
license-file="LICENSE"
edition = "2021"

[dependencies.bevy]
version = "0.8.0"
default-features = false

[dependencies]
serde = {version= "1.0.137"}
serde_json = {version= "1.0.81"}

entity = { path = "../../core/entity" }
data_converters = { path = "../../core/data_converters" }
server = { path = "../../core/server" }
networking = { path = "../../core/networking" }
