[package]
name = "asana"
version = "0.0.3"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description = "Automated Space Announcements."
homepage = "https://starwolves.io"
repository = "https://gitlab.starwolves.io/starwolves/space"
documentation = "https://docs.sf.starwolves.io"
license-file = "LICENSE"
edition = "2021"




[dependencies.bevy]
version = "0.11.3"

default-features = false

[dependencies]
chat = { path = "../../core/chat" }
player = { path = "../../core/player" }
resources = { path = "../../core/resources"}
networking = { path = "../../core/networking"}
ui = { path = "../../core/ui"}
