[package]
name = "asana"
version = "0.0.0"
edition = "2021"


[dependencies.bevy]
version = "0.7.0"
default-features = false

[dependencies]
connected_player = { path = "../../core/connected_player" }
pawn = { path = "../../core/pawn" }
api = { path = "../../core/api" }
