[package]
name = "gridmap"
version = "0.0.3-snap7-dev"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description="The map consisting of cells representing the ship."
homepage="https://starwolves.io"
repository="https://gitlab.starwolves.io/starwolves/space"
documentation="https://docs.sf.starwolves.io"
license-file="LICENSE"
edition = "2021"

[dependencies.bevy]
version = "0.8.1"
default-features = false

[dependencies]
bevy_rapier3d = "0.18.0"
doryen_fov = { path = "../doryen_fov" }
serde = {version= "1.0.145"}
serde_json = {version= "1.0.85"}

networking = { path = "../networking" }
networking_macros = { path = "../networking_macros" }
data_converters = { path = "../data_converters" }
entity = { path = "../entity" }
physics = { path = "../physics" }
actions = { path = "../actions" }
pawn = { path = "../pawn" }
data_link = { path = "../data_link" }
server = { path = "../server" }
math = { path = "../math" }
chat_api = { path = "../chat_api" }
