[package]
name = "gridmap"
version = "0.0.3-snap7-dev"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description="The map consisting of cells representing the ship."
homepage="https://starwolves.io"
repository="https://gitlab.starwolves.io/starwolves/space"
documentation="https://docs.sf.starwolves.io"
license-file="LICENSE"
edition = "2021"

[dependencies.bevy]
version = "0.8.0"
default-features = false

[dependencies]
bevy_rapier3d = "0.16.0"
doryen-fov = { git = "https://github.com/starwolfy/doryen-fov" }
serde = {version= "1.0.137"}
serde_json = {version= "1.0.81"}

networking = { path = "../networking" }
networking_macros = { path = "../networking_macros" }
health = { path = "../health" }
data_converters = { path = "../data_converters" }
entity = { path = "../entity" }
physics = { path = "../physics" }
api = { path = "../api" }
examinable = { path = "../examinable" }
actions = { path = "../actions" }
senser = { path = "../senser" }
pawn = { path = "../pawn" }
console_commands = { path = "../console_commands" }
