[package]
name = "gridmap"
version = "0.0.0"
edition = "2021"

[dependencies.bevy]
version = "0.8.0"
default-features = false

[dependencies]
bevy_rapier3d = "0.16.0"
doryen-fov = { git = "https://github.com/starwolfy/doryen-fov" }
const_format = "0.2.23"
rand = "0.8.5"
serde = {version= "1.0.137"}
serde_json = {version= "1.0.81"}

networking = { path = "../networking" }
health = { path = "../health" }
data_converters = { path = "../data_converters" }
entity = { path = "../entity" }
physics = { path = "../physics" }
api = { path = "../api" }
actions = { path = "../actions" }
