[package]
name = "gridmap"
version = "0.0.3-snap8-dev"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description = "The map consisting of cells representing the ship."
homepage = "https://starwolves.io"
repository = "https://gitlab.starwolves.io/starwolves/space"
documentation = "https://docs.sf.starwolves.io"
license-file = "LICENSE"
edition = "2021"

[features]
server = []
client = []

[dependencies.bevy]
version = "0.9.0"
default-features = false

[dependencies]
bevy_rapier3d = "0.19.0"
serde = "1.0.147"
serde_json = "1.0.87"
typename = "0.1.2"
ron = "0.8.0"

doryen_fov = { path = "../doryen_fov" }
networking = { path = "../networking", features = ["server"] }
entity = { path = "../entity", features = ["server"] }
actions = { path = "../actions", features = ["server"] }
pawn = { path = "../pawn", features = ["server"] }
resources = { path = "../resources", features = ["server"] }
math = { path = "../math", features = ["server"] }
text_api = { path = "../text_api", features = ["server"] }
player = { path = "../player", features = ["server"] }
physics = { path = "../physics", features = ["server"] }
