[package]
name = "combat"
version = "0.0.3-snap7-dev"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description="For combat and damage applications."
homepage="https://starwolves.io"
repository="https://gitlab.starwolves.io/starwolves/space"
documentation="https://docs.sf.starwolves.io"
license-file="LICENSE"
edition = "2021"

[dependencies.bevy]
version = "0.8.0"
default-features = false

[dependencies]
bevy_rapier3d = "0.16.0"
rand = "0.8.5"


networking = { path = "../networking" }
networking_macros = { path = "../networking_macros" }
health = { path = "../health" }
sounds = { path = "../../entities/sounds" }
physics = { path = "../physics" }
api = { path = "../api" }
gridmap = { path = "../gridmap" }
sfx = { path = "../sfx" }
inventory_item = { path = "../inventory_item" }
chat = { path = "../chat" }
examinable = { path = "../examinable" }
senser = { path = "../senser" }
