[package]
name = "combat"
version = "0.0.0"
edition = "2021"

[dependencies.bevy]
version = "0.8.0"
default-features = false

[dependencies]
bevy_rapier3d = "0.16.0"
rand = "0.8.5"


networking = { path = "../networking" }
health = { path = "../health" }
sounds = { path = "../../entities/sounds" }
physics = { path = "../physics" }
api = { path = "../api" }
gridmap = { path = "../gridmap" }
sfx = { path = "../sfx" }
inventory_item = { path = "../inventory_item" }
