[package]
name = "inventory"
version = "0.0.3-snap7-dev"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description="Inventory management of entities."
homepage="https://starwolves.io"
repository="https://gitlab.starwolves.io/starwolves/space"
documentation="https://docs.sf.starwolves.io"
license-file="LICENSE"
edition = "2021"

[dependencies.bevy]
version = "0.8.1"
default-features = false

[dependencies]
bevy_rapier3d = "0.16.2"
rand = "0.8.5"

networking = { path = "../networking" }
networking_macros = { path = "../networking_macros" }
sounds = { path = "../../entities/sounds" }
inventory_item = { path = "../inventory_item" }
inventory_api = { path = "../inventory_api" }
pawn = { path = "../pawn" }
physics = { path = "../physics" }
humanoid = { path = "../humanoid" }
sfx = { path = "../sfx" }

gridmap = { path = "../gridmap" }
actions = { path = "../actions" }
entity = { path = "../entity" }
server = { path = "../server" }
atmospherics = { path = "../atmospherics" }
math = { path = "../math" }
