[package]
name = "reflection_probe"
version = "0.0.3-snap8-dev"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description = "Manages client-side reflection graphics."
homepage = "https://starwolves.io"
repository = "https://gitlab.starwolves.io/starwolves/space"
documentation = "https://docs.sf.starwolves.io"
license-file = "LICENSE"
edition = "2021"


[features]
server = []
client = []

[dependencies.bevy]
version = "0.9.0"
default-features = false

[dependencies]
serde = "1.0.147"
serde_json = "1.0.87"

entity = { path = "../../core/entity", features = ["server"] }
resources = { path = "../../core/resources", features = ["server"] }
networking = { path = "../../core/networking", features = ["server"] }
