[package]
name = "reflection_probe"
version = "0.0.0"
edition = "2021"


[dependencies.bevy]
version = "0.8.0"
default-features = false

[dependencies]
serde = {version= "1.0.137"}
serde_json = {version= "1.0.81"}

entity = { path = "../../core/entity" }
inventory_item = { path = "../../core/inventory_item" }
data_converters = { path = "../../core/data_converters" }
api = { path = "../../core/api" }

