[package]
name = "pistol_l1"
version = "0.0.3"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description = "A projectile laser weapon."
homepage = "https://starwolves.io"
repository = "https://gitlab.starwolves.io/starwolves/space"
documentation = "https://docs.sf.starwolves.io"
license-file = "LICENSE"
edition = "2021"




[dependencies.bevy]
version = "0.11.2"

default-features = false

[dependencies]
bevy_xpbd_3d = { version = "0.2.0" , features = ["enhanced-determinism"], git = "https://github.com/Jondolf/bevy_xpbd.git", branch="main"}

entity = { path = "../../core/entity" }
text_api = { path = "../../core/text_api"}
combat = { path = "../../core/combat"}
resources = { path = "../../core/resources" }
physics = { path = "../../core/physics" }
inventory = { path = "../../core/inventory" }
basic_console_commands = { path = "../../core/basic_console_commands" }

