[package]
name = "pistol_l1"
version = "0.0.3"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description = "A projectile laser weapon."
homepage = "https://starwolves.io"
repository = "https://gitlab.starwolves.io/starwolves/space"
documentation = "https://docs.sf.starwolves.io"
license-file = "LICENSE"
edition = "2021"




[dependencies.bevy]
version = "0.10.0"
default-features = false

[dependencies]
bevy_rapier3d = "0.21.0"

entity = { path = "../../core/entity" }
text_api = { path = "../../core/text_api"}
combat = { path = "../../core/combat"}
resources = { path = "../../core/resources" }
physics = { path = "../../core/physics" }
inventory = { path = "../../core/inventory" }
basic_console_commands = { path = "../../core/basic_console_commands" }

