[package]
name = "chat"
version = "0.0.3-snap8-dev"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description="Chat managing proximity and radio communication."
homepage="https://starwolves.io"
repository="https://gitlab.starwolves.io/starwolves/space"
documentation="https://docs.sf.starwolves.io"
license-file="LICENSE"
edition = "2021"

[features]
server = []
client = []

[dependencies.bevy]
version = "0.8.1"
default-features = false

[dependencies]
voca_rs = "1.15.1"
bevy_renet = "0.0.5"
bincode = "1.3.3"

networking = { path = "../networking",  features=["server"] }
networking_macros = { path = "../networking_macros",  features=["server"] }
sfx = { path = "../sfx",  features=["server"] }
pawn = { path = "../pawn",  features=["server"] }
entity = { path = "../entity",  features=["server"] }
resources = { path = "../resources",  features=["server"] }
math = { path = "../math",  features=["server"] }
text_api = { path = "../text_api",  features=["server"] }
player = { path = "../player",  features=["server"] }
