[package]
name = "chat"
version = "0.0.3-snap7-dev"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description="Chat managing proximity and radio communication."
homepage="https://starwolves.io"
repository="https://gitlab.starwolves.io/starwolves/space"
documentation="https://docs.sf.starwolves.io"
license-file="LICENSE"
edition = "2021"

[dependencies.bevy]
version = "0.8.0"
default-features = false

[dependencies]
voca_rs = "1.14.0"

api = { path = "../api" }
networking = { path = "../networking" }
networking_macros = { path = "../networking_macros" }
sfx = { path = "../sfx" }
pawn = { path = "../pawn" }
entity = { path = "../entity" }
server = { path = "../server" }
math = { path = "../math" }
