[package]
name = "gi_probe"
version = "0.0.3-snap7-dev"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description="Manages client-side ambient occlusion."
homepage="https://starwolves.io"
repository="https://gitlab.starwolves.io/starwolves/space"
documentation="https://docs.sf.starwolves.io"
license-file="LICENSE"
edition = "2021"

[dependencies.bevy]
version = "0.8.1"
default-features = false

[dependencies]
serde = "1.0.147"
serde_json = "1.0.87"

entity = { path = "../../core/entity" }
data_converters = { path = "../../core/data_converters" }
server = { path = "../../core/server" }
networking = { path = "../../core/networking" }
