[package]
name = "jumpsuit_security"
version = "0.0.3"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description = "A wearable jumpsuit."
homepage = "https://starwolves.io"
repository = "https://gitlab.starwolves.io/starwolves/space"
documentation = "https://docs.sf.starwolves.io"
license-file = "LICENSE"
edition = "2021"




[dependencies.bevy]
version = "0.10.1"
default-features = false

[dependencies]
bevy_rapier3d = { version = "0.21.0", features = [
    "enhanced-determinism",
]}

entity = { path = "../../core/entity" }
combat = { path = "../../core/combat" }
resources = { path = "../../core/resources" }
physics = { path = "../../core/physics"}
inventory = { path = "../../core/inventory" }
basic_console_commands = { path = "../../core/basic_console_commands" }

