[package]
name = "player_controller"
version = "0.0.3-snap7-dev"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description="Logic regarding connected clients."
homepage="https://starwolves.io"
repository="https://gitlab.starwolves.io/starwolves/space"
documentation="https://docs.sf.starwolves.io"
license-file="LICENSE"
edition = "2021"
[dependencies.bevy]
version = "0.8.0"
default-features = false

[dependencies]
bevy_renet = "0.0.5"
bevy_rapier3d = "0.16.0"
bincode = "1.3.3"



networking = { path = "../networking" }
networking_macros = { path = "../networking_macros" }
entity = { path = "../entity" }
humanoid = { path = "../humanoid" }
inventory_item = { path = "../inventory_item" }
inventory_api = { path = "../inventory_api" }
pawn = { path = "../pawn" }
physics = { path = "../physics" }
console_commands = { path = "../console_commands" }
chat_api = { path = "../chat_api" }
map = { path = "../map" }
motd = { path = "../motd" }
chat = { path = "../chat" }
gridmap = { path = "../gridmap" }
world_environment = { path = "../world_environment" }
server = { path = "../server" }
showcase = { path = "../showcase" }
math = { path = "../math" }
gi_probe = { path = "../../entities/gi_probe" }
reflection_probe = { path = "../../entities/reflection_probe" }
