[package]
name = "player_controller"
version = "0.0.3-snap7-dev"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description="Logic regarding connected clients."
homepage="https://starwolves.io"
repository="https://gitlab.starwolves.io/starwolves/space"
documentation="https://docs.sf.starwolves.io"
license-file="LICENSE"
edition = "2021"
[dependencies.bevy]
version = "0.8.0"
default-features = false

[dependencies]
rand = "0.8.5"
bevy_renet = "0.0.5"
vector2math = "0.13.0"
bevy_rapier3d = "0.16.0"
bincode = "1.3.3"



networking = { path = "../networking" }
networking_macros = { path = "../networking_macros" }
entity = { path = "../entity" }
humanoid = { path = "../humanoid" }
inventory_item = { path = "../inventory_item" }
pawn = { path = "../pawn" }
rigid_body = { path = "../rigid_body" }
physics = { path = "../physics" }
console_commands = { path = "../console_commands" }
api = { path = "../api" }
map = { path = "../map" }
motd = { path = "../motd" }
chat = { path = "../chat" }
gridmap = { path = "../gridmap" }
examinable = { path = "../examinable" }
sensable = { path = "../sensable" }
health = { path = "../health" }
senser = { path = "../senser" }
world_environment = { path = "../world_environment" }
data_link = { path = "../data_link" }
server = { path = "../server" }
showcase = { path = "../showcase" }
math = { path = "../math" }
gi_probe = { path = "../../entities/gi_probe" }
reflection_probe = { path = "../../entities/reflection_probe" }
pistol_l1 = { path = "../../entities/pistol_l1" }
jumpsuit_security = { path = "../../entities/jumpsuit_security" }
helmet_security = { path = "../../entities/helmet_security" }
construction_tool_admin = { path = "../../entities/construction_tool_admin" }
