on: [push]

name: CI

jobs:
  build_and_test:
    name: Space Server
    runs-on: ubuntu-latest
    steps:
      - uses: rui314/setup-mold@v1
        with:
          make-default: false
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: link-arg=-fuse-ld=/usr/local/bin/mold
