[package]
name = "humanoid"
version = "0.0.3-snap8-dev"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description="Humanoid entities share animations and API."
homepage="https://starwolves.io"
repository="https://gitlab.starwolves.io/starwolves/space"
documentation="https://docs.sf.starwolves.io"
license-file="LICENSE"
edition = "2021"

[features]
server = []
client = []

[dependencies.bevy]
version = "0.8.1"
default-features = false

[dependencies]
bevy_rapier3d = "0.18.0"
vector2math = "0.13.0"

networking = { path = "../networking",  features=["server"] }
networking_macros = { path = "../networking_macros",  features=["server"] }
sounds = { path = "../../entities/sounds",  features=["server"] }
pawn = { path = "../pawn",  features=["server"] }
inventory_item = { path = "../inventory_item",  features=["server"] }
inventory_api = { path = "../inventory_api",  features=["server"] }
combat = { path = "../combat",  features=["server"] }
sfx = { path = "../sfx",  features=["server"] }
rigid_body = { path = "../rigid_body",  features=["server"] }
console_commands = { path = "../console_commands",  features=["server"] }
entity = { path = "../entity",  features=["server"] }
gridmap = { path = "../gridmap",  features=["server"] }
resources = { path = "../resources",  features=["server"] }
showcase = { path = "../showcase",  features=["server"] }
atmospherics = { path = "../atmospherics",  features=["server"] }
math = { path = "../math",  features=["server"] }
chat_api = { path = "../chat_api",  features=["server"] }
