[package]
name = "humanoid"
version = "0.0.3-snap8-dev"
authors = ["Nikita Ramses Abdoelrahman <ramses@starwolves.io>"]
description = "Humanoid entities share animations and API."
homepage = "https://starwolves.io"
repository = "https://gitlab.starwolves.io/starwolves/space"
documentation = "https://docs.sf.starwolves.io"
license-file = "LICENSE"
edition = "2021"



[dependencies.bevy]
version = "0.9.1"
default-features = false

[dependencies]
bevy_rapier3d = "0.19.0"
vector2math = "0.13.0"
bevy_renet = "0.0.6"
const_format = "0.2.30"

networking = { path = "../networking" }
sounds = { path = "../../entities/sounds" }
pawn = { path = "../pawn" }
combat = { path = "../combat" }
sfx = { path = "../sfx" }
entity = { path = "../entity" }
gridmap = { path = "../gridmap" }
resources = { path = "../resources" }
atmospherics = { path = "../atmospherics" }
math = { path = "../math" }
text_api = { path = "../text_api"}
controller = { path = "../controller" }
player = { path = "../player" }
physics = { path = "../physics" }
inventory = { path = "../inventory" }
